	DELETE FROM faq WHERE faq_sub_id=2;
	DELETE FROM video WHERE vid_sub_id=2;

	INSERT INTO `video` (`vid_sub_id`, `vid_id`, `vid_script`) VALUES
	(2, 24, 'There are approximately 4,800 recorded species, accounting for over 85% of extant amphibian species. '),
	(2, 25, 'The goliath frog, otherwise known as goliath bullfrog or giant slippery frog (Conraua goliath), is the largest living frog on Earth. Specimens can grow up to 32 cm (12.6 in) in length from snout to vent, and weigh up to 3.25 kg (7.17 lb). '),
	(2, 26, 'Some are and some are not. Frogs and toads come in a wide range of sizes. However, frogs are typically longer than toads. '),
	(2, 27, 'Frogs and toads will sit very still with their eyes closed. The assumption is that they are asleep, but it is not clear how long they sleep per day. '),
	(2, 28, 'Frogs hibernate to escape the freezing temperatures of winter. Their heartbeats and breathing slow, their body temperature drops to nearly match the outside temperature, and they pass the time in a state of dormancy or torpor. Aquatic frogs hibernate under water and take in oxygen from the water through their skin. They spend most of the winter lying on top of the bottom''s mud or partially buried in mud. At times, they may even slowly swim around. Terrestrial frogs normally hibernate on land. '),
	(2, 29, 'There are several theories on how frogs and toads choose their breeding ponds: 1. They return to the closest pond regardless of whether or not they originated from that pond. Although it is hard to keep track of individual frogs and toads, we can observe the numbers and the diversity of the amphibian populations in the ponds every year. 2. There a chemical clues left by other frogs and toads, especially the adults. 3. The light reflection varies from pond to pond. The frogs and toads may be selecting the different reflective qualities. 4.The frogs and toads may remember the way they left the pond. '),
	(2, 30, 'Frogs usually return to the pond in which they are born to reproduce but not always. '),
	(2, 31, 'Frogs and toads are carnivores, which means that they will eat meat. Small to medium sized frogs eat insects such as flies, mosquitoes, moths and dragonflies. Larger frogs will eat larger insects like grasshoppers and worms. Some large frogs will even eat small snakes, mice, baby turtles, and even other smaller frogs. '),
	(2, 32, 'Frogs lay eggs in water, and the eggs hatch into tadpoles that grow into frogs. '),
	(2, 33, 'All kinds of birds, snakes, lizards, skunks, hedgehogs, otters, minks, and us, the humans. Even other (larger) frogs eat frogs! '),
	(2, 34, 'Frogs need to be around areas with a water source to reproduce, but other than that, they are found on every continent except Antarctica and in almost every environment. '),
	(2, 35, 'A frog is any member of a diverse and largely carnivorous group of short-bodied, tailless amphibians composing the order Anura. '),
	(2, 36, 'There is no scientific distinction between frogs and toads but they do have specific traits that define them. For example, frogs are mostly aquatic; most toads live on land (but near water). Frogs have teeth; toads do not. Also, frogs have smooth, slimy skin; toads have dry, bumpy skin. Frogs are also typically longer than toads. '),
	(2, 37, 'Frogs can be kept as pets. '),
	(2, 38, 'Frog legs are rich in protein, omega-3 fatty acids, vitamin A, and potassium. They are often said to taste like chicken because of their mild flavor, with a texture most similar to chicken wings. The taste and texture of frog meat is approximately between chicken and fish. '),
	(2, 39, 'Frog legs are typically fried or sauteed. '),
	(2, 40, 'Kermit is the most famous frog. Other famous frogs include Michigan J. Frog, dat boi, hypnotoad, crazyfrog (not really a frog), and those frogs from the Budweiser commercial. '),
	(2, 41, 'The most popular frog names are Kermit, Frogger, and Lord Benedict McRibbit, Esquire. '),
	(2, 42, 'It varies by type of frog, with the average lifespan being between 4 and 15 years. '),
	(2, 43, 'A frog can become a prince by marrying into the royal family or if his father executes a hostile takeover of the kingdom. '),
	(2, 44, 'The average weight of the Common frog is 22.7g. The largest frog, the Goliath frog, can weigh more then 3 kg. '),
	(2, 45, 'You need some sort of magic spell or potion to turn a prince into a frog. '),
	(2, 46, 'A bio-indicator is any species or group of species whose function, population, or status can reveal the qualitative status of the environment. Frogs are good bio-indicators because they spend part of their life cycle on land and some in water.They have a permeable skin which allows substances to move relatively freely into its body and because they absorb and concentrate toxins in their fatty tissues. '),
	(2, 47, 'The bulging eyes of most frogs allow them to see in front, to the sides, and partially behind them. When a frog swallows food, it pulls its eyes down into the roof of its mouth. The eyes help push the food down its throat. '),
	(2, 48, 'Most frogs and toads breathe (and take in moisture) through their skin through a process called cutaneous gas exchange, but they also have lungs with which they breathe. '),
	(2, 49, 'Frogs do not have external ears like us. However, they do have eardrums and an inner ear. The frog ear is called a tympanum and is the circle you see behind a frog''s eye'),
	(2, 50, 'Frogs don''t use hearing to locate prey or danger, but listen to the other warning calls or mating calls of other frogs. When a frog comes across a threat they will call to warn other frogs of the danger. But hearing is mostly used in mating and territorial activities. '),
	(2, 51, 'Frogs can hear using big round ears on the sides of their head called a tympanum. Tympanum means drum. The size and distance between the ears depends on the wavelength and frequency of a male frogs call. '),
	(2, 52, 'A group of frogs is generally known as an army. '),
	(2, 53, 'Look for frogs near a water source like a pond or stream during the spring or summer. '),
	(2, 54, 'Their legs are long and slender; their toes have round pads, which help the frog grip and climb, and there is very little webbing between the toes, making them look quite long.  '),
	(2, 55, 'Its hard to determine the average volume of a frog so we cant calculate its density :(. '),
	(2, 56, 'Frogs are loudest during their mating season. '),
	(2, 57, 'The noise a frog makes is interpreted differently in different languages. In english a frog says "Ribbit", In japanese a frog says "Kero Kero". '),
	(2, 58, 'Frogs use their eyeballs to swallow. Frogs eat their prey whole and their eyeballs actually sink down into their mouth and push the food down into their throat. '),
	(2, 59, 'Frogs hibernate to escape the freezing temperatures of winter. Their heartbeats and breathing slow, their body temperature drops to nearly match the outside temperature, and they pass the time in a state of dormancy or torpor. Aquatic frogs hibernate under water and take in oxygen from the water through their skin. They spend most of the winter lying on top of the bottom''s mud or partially buried in mud. At times, they may even slowly swim around. Terrestrial frogs normally hibernate on land. '),
	(2, 60, 'When temperatures are cool, frogs need to bask in sunshine to warm up enough to be able to move. That''s because they are cold-blooded, which means their body temperature changes with the external temperature. '),
	(2, 61, 'Aquatic frogs hibernate under water and take in oxygen from the water through their skin. They spend most of the winter lying on top of the bottom''s mud or partially buried in mud. At times, they may even slowly swim around. Terrestrial frogs, including the spring peeper, normally hibernate on land. '),
	(2, 62, 'Frogs migrate when they go between their shallow summer breeding ponds and deeper lakes where they overwinter. '),
	(2, 63, 'Frogs (and toads) are beneficial to humans because they eat so many insect pests. They are also important environmental indicators. '),
	(2, 64, 'The number of frogs and toads around the world has been dropping. These declines have been connected with many causes: habitat loss and fragmentation, chemical pollution, increased ultraviolet radiation, acid precipitation, commercial harvest of frogs for food, and unknown causes. The decline in the number of frogs can be directly related to humans and their increasing demands on the environment. '),
	(2, 65, 'In August 1995 a large population of deformed Northern Leopard Frogs was discovered by a group of students from a Minnesota school. The discover became e a topic of national attention. Researchers from all over continue to seek answers to the "mystery of the deformed leopard frogs of LeSueur County." Some of the possible causes being investigated are pesticides and chemicals in the watershed; heavy metals in the soil; parasites; and genetic problems. '),
	(2, 66, 'During extensive periods of heat or drought, frogs keep from losing water by digging a burrow in the ground and entering a state of estivation - a period of dormancy or torpor. '),
	(2, 67, 'Its natural habitats are temperate forests, rivers, intermittent rivers, swamps, freshwater marshes, intermittent freshwater marshes, freshwater springs, ponds, open excavations, and canals and ditches. '),
	(2, 68, 'The goliath frog, otherwise known as goliath bullfrog or giant slippery frog (Conraua goliath), is the largest living frog on Earth. Specimens can grow up to 32 cm (12.6 in) in length from snout to vent, and weigh up to 3.25 kg (7.17 lb). '),
	(2, 69, 'A frog species that appears to be the world''s smallest has been discovered in Papua New Guinea by a US-based team. At 7mm (0.27 inches) long, Paedophryne amauensis may be the world''s smallest vertebrate - the group that includes mammals, fish, birds and amphibians. '),
	(2, 70, 'There are approximately 4,800 recorded species, accounting for over 85% of extant amphibian species. '),
	(2, 71, 'A tadpole is the larval stage in the life cycle of an amphibian, particularly that of a frog or toad. '),
	(2, 72, 'By between 12 to 16 weeks, depending on water and food supply, the frog has completed the full growth cycle. '),
	(2, 73, 'The type of habitat and food you should provide a frog varies widely by species. '),
	(2, 74, 'The type of habitat you should provide a frog varies widely by species. '),
	(2, 75, 'As pets, toads are generally far more responsive and aware than are their frog cousins.'),
	(2, 76, 'Nobody really knows! At this point in time, there has been very little research in frog sleep patterns. It is known that they close their eyes, but no confirming brain scans have determined whether or not they actually have a true sleep period. '),
	(2, 77, 'Frogs do not drink like we do; they absorb water directly through their skin in an area known as the drinking patch located on their belly and the underside of their thig'),
	(2, 78, 'Yes, many frogs can change color. Frogs change color to help hide from predators by matching the colors of their surroundings. The also change color to help control their body temperature as some colors absorb more or less light and can cool or warm them up. They use pigment cells called chromatophores to change color. Most frogs cannot completely change their color, instead they change the shade (lighter or darker) of their basic color. '),
	(2, 79, 'Some frogs are slimy because they are covered in a mucous coating. This coating helps them keep their skin moist which helps them breathe through their skin. The mucous often contains other chemicals, like antibacterial or anti fungals to help protect the frog. Other frogs actually secrete a waxy coating that they spread across their body to help retain moisture in areas that have high temperatures or if they are active during the day. '),
	(2, 80, 'Yes, frogs have lungs like we do and if their lungs fill with water, they can drown just like us. Frogs can also breathe through their skin. They need to keep their skin moist to be able to breathe through their skin, so if their skin dries out they are not able to absorb oxygen. They use their skin to absorb oxygen when underwater, but if there is not enough oxygen in the water, they will drown. '),
	(2, 81, 'Yes, frogs have a third eye lid that covers their eyes so they can keep them open underwater. The eyelid is called the nictitating membrane and also helps the eyes to stay moist when they are not in the water.');

	INSERT INTO `faq` (`faq_sub_id`, `faq_vid_id`, `faq_question`) VALUES
	(2, 24, 'How many species of frogs are there?'),
	(2, 25, 'What is the biggest type of frog?'),
	(2, 26, 'Are frogs bigger than toads?'),
	(2, 27, 'Do frogs or toads sleep?'),
	(2, 28, 'Is it true that frogs and toads hibernate in the winter?'),
	(2, 29, 'How do frogs and toads choose their breeding ponds?'),
	(2, 30, 'Do frogs always reproduce in the same pond?'),
	(2, 31, 'What do frogs eat?'),
	(2, 32, 'How do frogs reproduce?'),
	(2, 33, 'What kinds of animals eat frogs?'),
	(2, 34, 'Where do frogs live?'),
	(2, 35, 'What is the scientific name for frogs?'),
	(2, 36, 'What is the difference between a frog and toad?'),
	(2, 37, 'Can I have a pet frog?'),
	(2, 38, 'How does frog taste?'),
	(2, 39, 'How should I cook frog?'),
	(2, 40, 'Who is the most famous frog?'),
	(2, 41, 'What is the most popular frog name?'),
	(2, 42, 'How long do frogs live?'),
	(2, 43, 'How do you turn a frog into a prince?'),
	(2, 44, 'How much do frogs weigh?'),
	(2, 45, 'How do you turn a prince into a frog?'),
	(2, 46, 'Why are frogs referred to as bio-indicators?'),
	(2, 47, 'Why do frogs eyes bulge out?'),
	(2, 48, 'How do frogs breathe?'),
	(2, 49, 'How do frogs hear?'),
	(2, 50, 'How well do frogs hear?'),
	(2, 51, 'Can frogs hear?'),
	(2, 52, 'What is a group of frogs called?'),
	(2, 53, 'How can I find frogs?'),
	(2, 54, 'What is unique about the pacific treefrog?'),
	(2, 55, 'What is the average density of a frog?'),
	(2, 56, 'Why are frogs so loud in the spring?'),
	(2, 57, 'What does a frog say?'),
	(2, 58, 'How do frogs eat?'),
	(2, 59, 'Do frogs hibernate?'),
	(2, 60, 'Why do frogs sun themselves?'),
	(2, 61, 'Where do frogs go in the winter?'),
	(2, 62, 'Do frogs migrate?'),
	(2, 63, 'How are frogs beneficial?'),
	(2, 64, 'Why are scientists concerned about frogs?'),
	(2, 65, 'What is all the fuss about deformed frogs being found?'),
	(2, 66, 'If frogs have to have wet skin how do they survive during very hot or very dry spells?'),
	(2, 67, 'What is the natural habitat of mountain chorus frogs?'),
	(2, 68, 'Which species of frog is considered to be the worlds largest with its legs outstretched?'),
	(2, 69, 'Which frog is small enough to fit on your fingernail?'),
	(2, 70, 'How many types of frogs and toads are there?'),
	(2, 71, 'What are tadpoles?'),
	(2, 72, 'How long does it take before a tadpole turns into a frog?'),
	(2, 73, 'How do I raise frogs and what do I feed them?'),
	(2, 74, 'What kind of habitat do I provide for my frog?'),
	(2, 75, 'Are frogs or toads better pets?'),
	(2, 76, 'Do frogs sleep?'),
	(2, 77, 'Do frogs drink water?'),
	(2, 78, 'Can frogs change color?'), 
	(2, 79, 'Why are frogs slimy?'),
	(2, 80, 'Can a frog drown?'),
	(2, 81, 'Can frogs see underwater?');
